{% set version = "0.2.4" %}

package:
  name: snaptime
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/snaptime/snaptime-{{ version }}.tar.gz
  sha256: e3f1eb89043d58d30721ab98cb65023f1a4c2740e3b197704298b163c92d508b

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - python-dateutil
    - pytz

test:
  requires:
    - python {{ python_min }}
  imports:
    - snaptime

about:
  home: https://github.com/zartstrom/snaptime
  license: MIT
  license_file: {{ RECIPE_DIR }}/LICENSE.txt
  summary: Transform timestamps with a simple DSL

extra:
  recipe-maintainers:
    - ocefpaf
