travis:
  secure:
    BINSTAR_TOKEN: v2VIJz/3O+BC9bE3+HhNV8pcbIXGO8culyzB8MlHG+Wfm2Pc9MQP0NnXBP5WD257aMzOJr5hI2bFoIbskpfDkRWzxMdiH+qR+x4gLvFodbnjqvYtyzQejBrX6Tc+DvymNX9Xy9PSf24S09qwblLCWDTZfOibNuPOIT/ZNkJlDBifhstd2IcKJBiY05r84HOtRbV8Ke6LduPpN32w7r+9994xXvuh3CesaCnBKRsHdkDRbn9Vx2GfYqCCZGchnBIgJyUSJevakIY/4+KL7Z+Z8swdkEJXgerZ4pXuWmG/DNGTYQFSKCSupHLuQoQvWyJRwwZBaIqIR5QwnLUExm89C8RlLokPsUlVNZDcsPJRvjN+Nytl3Nk3Jo2TDJ6mDNoReglujOt62nNGjf7ANlwiHcju8iIyvJOFkd3CZSN2N3Le/rPmwJ45CzxJT1tb1/2seEOUlCLJgNAdbdY2kanlaZrJWGwNttIRIim3MaeWNlcm/7pLm5YIATJ1hGyeL6kWG+CBsdrCgfPEwFTleInlZTIBBrujQekY73XsRJNDTyluRQYa+doZWG7rInWb1wogytx/1sRga+7sEpP0mxZO4mgv5/lPmAsi7eS9q3Jtd8Eib9KYLV0g3vrcpSV1P9HpHVWLUrIc22O9vlFURz0Ebonv/gy9bQTEisTXLY5Pcw8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
