travis:
  secure:
    BINSTAR_TOKEN: XXxbiAQ6oPeJtPXWWsfuXs+f/PPvTfFuOyNi0rv6MygbQtVy4wk++bpQw0xnQx37hRdYFr5EcHShTSLoLIu0sTDgVJzb4BhtaR89x7bNdhMF+8r9ayF4z1DAzZR77PWsXPrkMjlyJqqMA0IGvs6p3jw/gS8Nt1DCjGfV5cVPVqE7BFLuUODGDZf9OmDGWNUgR3anbfLw79styM9Rxi+PTtJ/QPfzYcGnFLQZyLsvQ73tUix7yLmF21wX6xNW0hZ6kkaoIGeKDsxV/aLpT/mblhcGwxvCIN7eLyTOQC52gVNTA7a13vGkVJnKoulRzQxWpIFOwnN2hzVqOt3bUQz6ZKf1wucgLfB41gHHEPSvzM1rdev55Grp1ihDuS6k0m1rwEiDqy7peu4ZQsvB8Q5J5COVCS8fIzE8wkLl3DRuUXpcK/2N5ybHxY1D0+3bsORzi4E07nH1ZPUICklxyn0ETPUkTkXACHvMbdWRlQRf2JM1ORZhPBFUDYufTZiiQsFKe5HJszIA0Lah9FicADU0oSjfyvdYuwvL1yNKBnQNMxmyjh75bz+TUscNUp3FCYpJagGOBPlqLmPfu3uj+J6VFR6LuDExf/XloZumM2xsFE5bDsJThFP7N8f5xJ24XA0MyikjKBBiz32I5H/2knRL4R70ghqRgCLE700FkLFoz6c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
